# ─────────────────────────────────────
# NiB – Cloudflare Worker
# ─────────────────────────────────────

name = "nib-archiv"
main = "index.js"
compatibility_date = "2026-08-24"


# ─────────────────────────────────────
# D1-Datenbank
# ─────────────────────────────────────

[[d1_databases]]
binding = "DB"
database_name = "nib-daten"
database_id = "9d21cf05-7f02-4cc1-800f-48df6bbba914"


# ─────────────────────────────────────
# KV – Admin-Sessions
# ─────────────────────────────────────

[[kv_namespaces]]
binding = "SESSIONS"
id = "640cb47f4897497086d13c456ade2020"


# ─────────────────────────────────────
# Cloudinary
# ─────────────────────────────────────

[vars]
CLOUDINARY_CLOUD_NAME = "r9tk5wns"


# ─────────────────────────────────────
# Observability
# ─────────────────────────────────────

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
